Add mvn wrapper properties file
digital-asset/custom-views pull request #6
Opened 2022-11-30 17:04 UTC by fayi-da

2022-11-30 17:06 UTC, chunlokling-da approved these changes

2022-11-30 17:11 UTC, ray-roestenburg-da requested changes
Prefer to remove mvn wrapper and add to the readme that this project uses maven.

2022-11-30 17:39 UTC, chunlokling-da commented
> Add to the readme that this project uses maven.

added in this PR https://github.com/digital-asset/custom-views/pull/5/files#diff-5d176b8a174dbf132271a4bf774eaa7189da6137ab2a0d0b791e34ae4c1ea64aR12

2022-12-01 11:39 UTC, fayi-da commented
Closing this PR in favour of #5

2022-12-01 11:39 UTC, closed without merging